-- ============================================================
-- Ygeiopolis Hospital - Synthetic Data
-- Generated by generate_data.py
-- ============================================================

SET FOREIGN_KEY_CHECKS = 0;
SET NAMES utf8mb4;

-- ------------------------------------------------------------
-- Clearing all tables before insert
-- ------------------------------------------------------------
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM patient_review_doctor;
ALTER TABLE patient_review_doctor AUTO_INCREMENT = 1;
DELETE FROM patient_review_hospitalization;
ALTER TABLE patient_review_hospitalization AUTO_INCREMENT = 1;
DELETE FROM prescription;
ALTER TABLE prescription AUTO_INCREMENT = 1;
DELETE FROM procedure_staff;
ALTER TABLE procedure_staff AUTO_INCREMENT = 1;
DELETE FROM medical_procedure;
ALTER TABLE medical_procedure AUTO_INCREMENT = 1;
DELETE FROM lab_test;
ALTER TABLE lab_test AUTO_INCREMENT = 1;
DELETE FROM hospitalization;
ALTER TABLE hospitalization AUTO_INCREMENT = 1;
DELETE FROM triage;
ALTER TABLE triage AUTO_INCREMENT = 1;
DELETE FROM shift_assignment;
ALTER TABLE shift_assignment AUTO_INCREMENT = 1;
DELETE FROM shift;
ALTER TABLE shift AUTO_INCREMENT = 1;
DELETE FROM operating_room;
ALTER TABLE operating_room AUTO_INCREMENT = 1;
DELETE FROM bed;
ALTER TABLE bed AUTO_INCREMENT = 1;
DELETE FROM doctor_department;
ALTER TABLE doctor_department AUTO_INCREMENT = 1;
DELETE FROM doctor;
ALTER TABLE doctor AUTO_INCREMENT = 1;
DELETE FROM nurse;
ALTER TABLE nurse AUTO_INCREMENT = 1;
DELETE FROM admin_staff;
ALTER TABLE admin_staff AUTO_INCREMENT = 1;
DELETE FROM staff;
ALTER TABLE staff AUTO_INCREMENT = 1;
DELETE FROM patient;
ALTER TABLE patient AUTO_INCREMENT = 1;
DELETE FROM department;
ALTER TABLE department AUTO_INCREMENT = 1;
SET FOREIGN_KEY_CHECKS = 1;